import pandas as pd
import numpy as np
import joblib
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, mean_absolute_error

# 1. SETUP PATHS
ROOT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT_DIR / 'data' / 'modeling'
MODEL_EXPORT_PATH = ROOT_DIR / 'models'
MODEL_EXPORT_PATH.mkdir(exist_ok=True)

def engineer_advanced_features(df, historical_df=None):
    """
    Calculates the 'F1 Logic' features: 
    Track History, Overtake-ability, and Team/Driver weighting.
    """
    # If we are processing test data, we use the training set for historical context
    ref_df = historical_df if historical_df is not None else df
    
    # --- CIRCUIT CRITERIA: Overtake-ability ---
    # Tracks where people gain positions have high 'passability'
    circuit_pass = ref_df.groupby('race_name')['pos_gain_loss'].mean().to_dict()
    df['circuit_passability'] = df['race_name'].map(circuit_pass).fillna(0)

    # --- DRIVER CRITERIA: Track-Specific Performance ---
    # How has this driver specifically performed at THIS circuit in the past?
    driver_track = ref_df.groupby(['driverRef', 'race_name'])['positionOrder'].mean().reset_index()
    driver_track = driver_track.rename(columns={'positionOrder': 'driver_track_history'})
    df = df.merge(driver_track, on=['driverRef', 'race_name'], how='left')
    df['driver_track_history'] = df['driver_track_history'].fillna(12) # Default mid-pack

    # --- TEAM CRITERIA: Historical Power (Lower Relevance) ---
    # Long-term average performance of the team
    team_hist = ref_df.groupby('constructor_name')['positionOrder'].mean().to_dict()
    df['team_history'] = df['constructor_name'].map(team_hist).fillna(12)
    
    return df

def train_and_export():
    # Load the files generated by merge_training.py
    train_df = pd.read_csv(DATA_DIR / 'train_f1_2017_2022.csv')
    test_df = pd.read_csv(DATA_DIR / 'test_f1_2023_2024.csv')

    # Apply Advanced Engineering
    print("Engineering Advanced Criteria (Track History, Passability, Team Power)...")
    train_df = engineer_advanced_features(train_df)
    test_df = engineer_advanced_features(test_df, historical_df=train_df)

    # FEATURES LIST (The criteria your model uses)
    # Includes: Grid, Recent Form (EWMA), Track History, Team Form, Team History, and Track Passability
    FEATURES = [
        'grid', 'driver_form', 'driver_track_history', 
        'team_form', 'team_history', 'circuit_passability',
        'driver_points_pre_race', 'driver_pos_pre_race'
    ]

    X_train = train_df[FEATURES]
    X_test = test_df[FEATURES]

    # --- MODEL 1: TOP 3 PROBABILITY (Podium) ---
    print("Training Podium Classifier...")
    podium_clf = RandomForestClassifier(n_estimators=150, max_depth=10, random_state=42)
    podium_clf.fit(X_train, train_df['top3'])
    
    # --- MODEL 2: TOP 10 PROBABILITY (Points) ---
    print("Training Points Classifier...")
    points_clf = RandomForestClassifier(n_estimators=150, max_depth=10, random_state=42)
    points_clf.fit(X_train, train_df['top10'])

    # --- MODEL 3: FINISHING POSITION (Regression) ---
    print("Training Position Regressor...")
    pos_reg = RandomForestRegressor(n_estimators=150, max_depth=10, random_state=42)
    pos_reg.fit(X_train, train_df['positionOrder'])

    # EXPORT EVERYTHING
    print(f"Exporting models to {MODEL_EXPORT_PATH}...")
    joblib.dump(podium_clf, MODEL_EXPORT_PATH / 'podium_clf.joblib')
    joblib.dump(points_clf, MODEL_EXPORT_PATH / 'points_clf.joblib')
    joblib.dump(pos_reg, MODEL_EXPORT_PATH / 'pos_reg.joblib')
    
    # Export the engineered test data for the app to use
    test_df.to_csv(MODEL_EXPORT_PATH / 'app_data_advanced.csv', index=False)

    # Performance Check
    preds_pos = pos_reg.predict(X_test)
    print(f"\nFinal Model Accuracy (MAE): {mean_absolute_error(test_df['positionOrder'], preds_pos):.2f} positions")
    print("Ready for Website deployment!")

if __name__ == "__main__":
    train_and_export()